# Biến mọi lỗi định dạng thành Cảnh báo (Warning) thay vì lỗi chặn build (Error)
warning_threshold: 9999

# Tắt bỏ hoàn toàn các quy tắc quá khắt khe vừa báo lỗi
disabled_rules:
  - superfluous_disable_command
  - orphaned_doc_comment
  - large_tuple

identifier_name:
  min_length:
    warning: 1 # Cho phép biến ngắn 1 ký tự như 'i'
    error: 1
  excluded:
    - id
    - cx
    - cy
    - ex
    - ey
    - sz
    - px
    - ac
    - i

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true
