# Biến TẤT CẢ các lỗi vi phạm của mọi quy tắc thành Cảnh báo (Warning)
only_warnings: true

# Thiết lập ngưỡng lỗi chặn build lên vô hạn để không bao giờ làm sập tiến trình build nữa
warning_threshold: 99999
error_threshold: 99999

# Tắt bỏ hoàn toàn các quy tắc quét nghiêm ngặt nhất
disabled_rules:
  - superfluous_disable_command
  - orphaned_doc_comment
  - large_tuple
  - closure_parameter_position
  - identifier_name
  - line_length
